### ISSUE TITLE
Sniadanie Roota.

### ISSUE THREAD

**Issue by iamsaltish** [smrootbot/smroot#30]
Nalezy dodac do AI ewentualna odpowiedz (jezeli root ma humor) na pytanie o jego sniadanie.
![1_mrsaqh0sjsrr16spm1qikq](https://user-images.githubusercontent.com/32518770/35701293-728d5676-078d-11e8-9a86-3523e278dd75.jpg)

**Comment by iamsaltish** [comment]
@xdk78 @takidelfin

**Comment by RootKlawiter** [comment]
Jestem za, dawajcie chłopaki

**Comment by takidelfin** [comment]
OK, wpartole to.
